[app]
local_folder = "~/Chem/doc/projects"
script_folder = "~/.config/recli/scripts"
parser_folder = "~/.config/recli/parsers"

[remotes.jupiter]
host = "150.162.31.2"
user = "vport"
port = "2222"
parser = "PBS.py"
queue_script = "qprep_jupiter.sh"
remote_folder = "/home/vport/projects"

[remotes.newton]
host = "newton.cesup.ufrgs.br"
user = "vport"
port = ""
parser = "PBS.py"
queue_script = "qprep_newton.sh"
remote_folder = "/mnt/data/vport/projects"

