[local]
projects_folder = "/home/vport/projects"
# submit_commands = ["pueue", "add", "--", "job", "$inpfile"]

[[remotes]]
name = "jupiter"
user = "vport"
work_directory = "/scratch/vport"
# queue-manager = "pbs"
# submit_commands = []

[[remotes]]
name = "trindatimes"
user = "vport"
work_directory = "/home/vport/projects"
# queue-manager = "pueue"
# submit_commands = ["pueue", "add", "--", "job", "$inpfile"]
